### ISSUE TITLE
Issue installing with NPM

### ISSUE THREAD

**Issue by twing207** [firepick/jspcb#1]
`/usr/local/bin/jspcb -> /usr/local/lib/node_modules/jspcb/bin/jspcb.js

> phantomjs-prebuilt@2.1.15 install /usr/local/lib/node_modules/jspcb/node_modules/phantomjs-prebuilt
> node install.js

Considering PhantomJS found at /usr/local/bin/phantomjs
Looks like an `npm install -g`
Found PhantomJS at /usr/local/lib/node_modules/phantomjs/lib/phantom/bin/phantomjs ...verifying
Writing location.js file
Error checking path, continuing { Error: EACCES: permission denied, open '/usr/local/lib/node_modules/jspcb/node_modules/phantomjs-prebuilt/lib/location.js'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.writeFileSync (fs.js:1333:33)
    at writeLocationFile (/usr/local/lib/node_modules/jspcb/node_modules/phantomjs-prebuilt/lib/util.js:84:6)
    at Promise._successFn (/usr/local/lib/node_modules/jspcb/node_modules/phantomjs-prebuilt/install.js:366:11)
    at nextTickCallback (/usr/local/lib/node_modules/jspcb/node_modules/kew/kew.js:47:28)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/usr/local/lib/node_modules/jspcb/node_modules/phantomjs-prebuilt/lib/location.js' }
Download already available at /tmp/phantomjs/phantomjs-2.1.1-macosx.zip
Verified checksum of previously downloaded file
Extracting zip contents
Removing /usr/local/lib/node_modules/jspcb/node_modules/phantomjs-prebuilt/lib/phantom
Copying extracted folder /tmp/phantomjs/phantomjs-2.1.1-macosx.zip-extract-1506633642580/phantomjs-2.1.1-macosx -> /usr/local/lib/node_modules/jspcb/node_modules/phantomjs-prebuilt/lib/phantom
Phantom installation failed { Error: EACCES: permission denied, link '/tmp/phantomjs/phantomjs-2.1.1-macosx.zip-extract-1506633642580/phantomjs-2.1.1-macosx' -> '/usr/local/lib/node_modules/jspcb/node_modules/phantomjs-prebuilt/lib/phantom'
    at Error (native)
  errno: -13,
  code: 'EACCES',
  syscall: 'link',
  path: '/tmp/phantomjs/phantomjs-2.1.1-macosx.zip-extract-1506633642580/phantomjs-2.1.1-macosx',
  dest: '/usr/local/lib/node_modules/jspcb/node_modules/phantomjs-prebuilt/lib/phantom' } Error: EACCES: permission denied, link '/tmp/phantomjs/phantomjs-2.1.1-macosx.zip-extract-1506633642580/phantomjs-2.1.1-macosx' -> '/usr/local/lib/node_modules/jspcb/node_modules/phantomjs-prebuilt/lib/phantom'
    at Error (native)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phantomjs-prebuilt@2.1.15 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs-prebuilt@2.1.15 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

`

**Comment by twing207** [comment]
I am getting the above error when trying to install this using NPM.

**Comment by twing207** [comment]
I found the problem. My usr/local/ ownership was my user but I was using sudo to install. Make sure you are installing as the owner of usr/local/

**Comment by firepick1** [comment]
Thanks for researching the issue. The EACCES message was revealing. Sorry for the delay in responding. Looks like you're solved.
